### PR TITLE
Sm/no-json-in-table

### PR DESCRIPTION
**Pull request by mshanemc**
### What does this PR do?
1. use the correct property from the coverage results
2. pull in color enhancements from https://github.com/salesforcecli/plugin-source/pull/934/
3. share 1 coverage table between both mdapi and source result formatters
4. improve UT coverage of the human output generation function

### What issues does this PR fix or reference?
https://github.com/forcedotcom/cli/issues/2468
@W-14123241@

### CODE REVIEW

**Review by cristiand391 — APPROVED** [review]

**Comment by cristiand391** [comment]
**QA notes**:

✅ uncovered lines column in apex code cov table is properly formatted
**before**
```
➜  dreamhouse-lwc git:(main) ✗ sf force source deploy report --jobid 0AfDH00001qld0n0AA --verbose
Warning: We plan to deprecate this command in the future. Try using the "project deploy start" and "project deploy report" pair instead.
...
=== Apex Code Coverage

 Name               % Covered Uncovered Lines
 ────────────────── ───────── ────────────────────────────────────────────────────────────────────────────────────────────────────────────
 PagedResult        100%      []
 PropertyController 95%       [ { column: 0, line: 26, numExecutions: 0, time: -1 }, { column: 0, line: 31, numExecutions: 0, time: -1 } ]
```
**after** (plugin-source linked)
```
➜  dreamhouse-lwc git:(main) ✗ sf force source deploy report --jobid 0AfDH00001qld0
n0AA --verbose
Warning: We plan to deprecate this command in the future. Try using the "project deploy start" and "project deploy report" pair instead.
Deploy ID: 0AfDH00001qld0n0AA
...
=== Apex Code Coverage

 Name               % Covered Uncovered Lines
 ────────────────── ───────── ───────────────
 PagedResult        100%
 PropertyController 95%       26,31
```
✅ json output still valid:
```
➜  dreamhouse-lwc git:(main) ✗ sf force source deploy report --jobid 0AfDH00001qld0n0AA --verbose --json | jq '.result.details.runTestResult.codeCoverage[1]'
{
  "id": "01pDH00000JRMCtYAP",
  "locationsNotCovered": [
    {
      "column": 0,
      "line": 26,
      "numExecutions": 0,
      "time": -1
    },
    {
      "column": 0,
      "line": 31,
      "numExecutions": 0,
      "time": -1
    }
  ],
  "name": "PropertyController",
  "namespace": null,
  "numLocations": 44,
  "numLocationsNotCovered": 2,
  "type": "Class",
  "dmlInfo": [],
  "methodInfo": [],
  "soqlInfo": [],
  "soslInfo": []
}
```

✅ color output in code cov table

**Comment by AllanOricil** [comment]
I wasnt added as a contributo by github 😭😡

**Comment by cristiand391** [comment]
I see you here 😛 

https://github.com/salesforcecli/plugin-source/graphs/contributors

Screenshot 2023-09-22 at 16 50 33

**Comment by AllanOricil** [comment]
Weird. Maybe I don't see it on the app because it displays cached data. But thanks anyway ❤

**Pull request merged**
